"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Source = { id: string; name: string; status: string; allowImport: boolean; type: string };
type Preview = { totalRows: number; preview: Array<{ rowNumber: number; status: string; displayName: string | null; platform: string | null; profileUrl: string | null; errorCode: string | null; errorMessage: string | null }>; errors: Array<{ rowNumber: number; errorCode?: string; errorMessage?: string }> };
const platformLabels: Record<string, string> = { XIAOHONGSHU: "小红书", YOUTUBE: "YouTube", X: "X", DOUYIN: "抖音" };

export default function ImportsPage() {
  const [sources, setSources] = useState<Source[]>([]); const [sourceId, setSourceId] = useState(""); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [batchId, setBatchId] = useState("");
  useEffect(() => { fetch("/api/sources").then(async (response) => { if (response.ok) { const data = await response.json(); setSources(data.items); } }); }, []);
  async function previewFile() { if (!file || !sourceId) { setError("请选择获准来源和 CSV 文件"); return; } setBusy(true); setError(""); setPreview(null); const form = new FormData(); form.set("file", file); form.set("sourceId", sourceId); try { const response = await fetch("/api/imports/preview", { method: "POST", headers: { Origin: window.location.origin }, body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "预览失败"); setPreview(data); } catch (err) { setError(err instanceof Error ? err.message : "预览失败"); } finally { setBusy(false); } }
  async function submitImport() { if (!file || !sourceId) return; setBusy(true); setError(""); const form = new FormData(); form.set("file", file); form.set("sourceId", sourceId); try { const response = await fetch("/api/imports", { method: "POST", headers: { Origin: window.location.origin, "Idempotency-Key": crypto.randomUUID() }, body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "导入失败"); setBatchId(data.item.id); } catch (err) { setError(err instanceof Error ? err.message : "导入失败"); } finally { setBusy(false); } }
  function downloadTemplate() { const blob = new Blob(["platform,nativeId,displayName,profileUrl,organization,serviceTags,region,sourceUrl\nYOUTUBE,demo-001,演示财富规划机构,https://example.com/demo/youtube/001,演示机构,海外资产配置|财富规划,新加坡,https://example.com/demo/source/001\n"], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "accounts-template.csv"; anchor.click(); URL.revokeObjectURL(url); }
  return <main className="page"><div className="page-header"><div><h1 className="page-title">导入中心</h1><p className="page-subtitle">先预览，再提交。每批导入最多 500 行、2 MiB；只接受账号资料，不接受联系方式列。</p></div><button className="button secondary" onClick={downloadTemplate}>下载 CSV 模板</button></div><section className="card"><div className="form-grid"><div className="field"><label htmlFor="source">获准数据来源</label><select id="source" value={sourceId} onChange={(e) => setSourceId(e.target.value)}><option value="">请选择来源</option>{sources.map((source) => <option key={source.id} value={source.id} disabled={source.status !== "APPROVED" || !source.allowImport}>{source.name}（{source.status === "APPROVED" && source.allowImport ? "可录入" : "未获准"}）</option>)}</select></div><div className="field"><label htmlFor="file">CSV 文件</label><input id="file" type="file" accept=".csv,text/csv" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setPreview(null); setBatchId(""); }} /></div><div className="notice full">上传主页链接只做本地格式和平台路径校验，不会由服务器访问、展开或抓取链接。</div>{error ? <div className="notice error full">{error}</div> : null}<div className="form-actions full"><button className="button" onClick={() => void previewFile()} disabled={busy || !file || !sourceId}>{busy ? "处理中…" : "预览导入"}</button></div></div></section>{preview ? <section className="card" style={{ marginTop: 18 }}><div className="page-header" style={{ marginBottom: 14 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>预览结果</h2><p className="page-subtitle">共 {preview.totalRows} 条数据行，以下展示前 20 行；预览阶段未写入数据库。</p></div>{preview.errors.length === 0 ? <button className="button" onClick={() => void submitImport()} disabled={busy}>确认导入</button> : <span className="badge warning">存在错误，请修正文件</span>}</div>{preview.errors.length ? <div className="notice error">发现 {preview.errors.length} 条可定位错误：{preview.errors.slice(0, 10).map((item) => `第 ${item.rowNumber} 行 ${item.errorMessage ?? item.errorCode}`).join("；")}</div> : null}<div className="table-wrap"><table><thead><tr><th>CSV 行</th><th>状态</th><th>平台</th><th>账号名称</th><th>主页</th><th>说明</th></tr></thead><tbody>{preview.preview.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td><span className={`badge ${row.status === "READY" ? "success" : row.status === "DUPLICATE" ? "neutral" : "danger"}`}>{row.status}</span></td><td>{row.platform ? platformLabels[row.platform] : "—"}</td><td>{row.displayName ?? "—"}</td><td className="mono">{row.profileUrl ?? "—"}</td><td>{row.errorMessage ?? "—"}</td></tr>)}</tbody></table></div></section> : null}{batchId ? <div className="notice success" style={{ marginTop: 18 }}>导入已完成：<Link className="text-link" href={`/imports/${batchId}`}>查看导入结果</Link></div> : null}</main>;
}
