"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

const labels: Record<string, string> = { XIAOHONGSHU: "小红书", YOUTUBE: "YouTube", X: "X", DOUYIN: "抖音" };
type Account = { id: string; platform: string; nativeId: string | null; displayName: string; profileUrl: string; normalizedProfileUrl: string; organization: string | null; serviceTags: string[]; region: string | null; sourceId: string; sourceUrl: string; capturedAt: string; createdAt: string; updatedAt: string; isDemo: boolean; source: { name: string; type: string; status: string; allowImport: boolean; permissionNote: string; expiresAt: string | null } };

export function AccountDetail({ id }: { id: string }) {
  const [account, setAccount] = useState<Account | null>(null); const [form, setForm] = useState({ displayName: "", organization: "", serviceTags: "", region: "" }); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { fetch(`/api/accounts/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) { setError(data.message ?? "账号加载失败"); return; } setAccount(data.item); setForm({ displayName: data.item.displayName, organization: data.item.organization ?? "", serviceTags: data.item.serviceTags.join("|"), region: data.item.region ?? "" }); }); }, [id]);
  async function save(event: FormEvent) { event.preventDefault(); setError(""); setSaved(false); const response = await fetch(`/api/accounts/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Origin: window.location.origin }, body: JSON.stringify({ displayName: form.displayName, organization: form.organization || null, serviceTags: form.serviceTags.split("|").map((tag) => tag.trim()).filter(Boolean), region: form.region || null }) }); const data = await response.json(); if (!response.ok) { setError(data.message ?? "保存失败"); return; } setAccount(data.item); setSaved(true); }
  if (error && !account) return <main className="page"><div className="notice error">{error}</div><Link className="text-link" href="/accounts">返回账号库</Link></main>;
  if (!account) return <main className="page"><div className="empty">正在加载账号…</div></main>;
  return <main className="page"><div className="page-header"><div><h1 className="page-title">{account.displayName}</h1><p className="page-subtitle">账号详情 · {labels[account.platform] ?? account.platform}{account.isDemo ? " · 演示数据" : ""}</p></div><Link className="button secondary" href="/accounts">返回账号库</Link></div><section className="card" style={{ marginBottom: 18 }}><dl className="detail-grid"><div className="detail-item"><dt>平台账号 ID</dt><dd>{account.nativeId || "未提供"}</dd></div><div className="detail-item"><dt>数据来源</dt><dd>{account.source.name} <span className={`badge ${account.source.status === "APPROVED" ? "success" : "warning"}`}>{account.source.status}</span></dd></div><div className="detail-item"><dt>主页链接</dt><dd><a className="text-link" href={account.profileUrl} target="_blank" rel="noreferrer noopener">主动打开主页 ↗</a></dd></div><div className="detail-item"><dt>来源证据链接</dt><dd><a className="text-link" href={account.sourceUrl} target="_blank" rel="noreferrer noopener">主动打开来源 ↗</a></dd></div><div className="detail-item"><dt>服务标签</dt><dd><div className="tag-list">{account.serviceTags.length ? account.serviceTags.map((tag) => <span className="tag" key={tag}>{tag}</span>) : "未填写"}</div></dd></div><div className="detail-item"><dt>公开服务地区</dt><dd>{account.region || "未填写"}</dd></div><div className="detail-item"><dt>录入时间</dt><dd>{new Date(account.createdAt).toLocaleString("zh-CN")}</dd></div><div className="detail-item"><dt>捕获时间</dt><dd>{new Date(account.capturedAt).toLocaleString("zh-CN")}</dd></div></dl></section><section className="card"><h2 style={{ marginTop: 0, fontSize: 18 }}>维护业务资料</h2><p className="muted small">本轮只允许修改展示资料，不允许通过编辑更换平台身份或数据来源。</p><form className="form-grid" onSubmit={save}><div className="field"><label htmlFor="displayName">账号名称</label><input id="displayName" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} required /></div><div className="field"><label htmlFor="organization">机构</label><input id="organization" value={form.organization} onChange={(e) => setForm({ ...form, organization: e.target.value })} /></div><div className="field"><label htmlFor="serviceTags">服务标签（用 | 分隔）</label><input id="serviceTags" value={form.serviceTags} onChange={(e) => setForm({ ...form, serviceTags: e.target.value })} /></div><div className="field"><label htmlFor="region">公开服务地区</label><input id="region" value={form.region} onChange={(e) => setForm({ ...form, region: e.target.value })} /></div>{error ? <div className="notice error full">{error}</div> : null}{saved ? <div className="notice success full">已保存。</div> : null}<div className="form-actions full"><button className="button">保存资料</button></div></form></section></main>;
}
