"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

type Source = { id: string; name: string; status: string; allowImport: boolean; type: string };
type Preview = { totalRows: number; preview: Array<{ rowNumber: number; status: string; displayName: string | null; platform: string | null; profileUrl: string | null; errorCode: string | null; errorMessage: string | null }>; errors: Array<{ rowNumber: number; errorCode?: string; errorMessage?: string }> };
type Snapshot = { file: File; sourceId: string; operationKey: string };
const platformLabels: Record<string, string> = { XIAOHONGSHU: "小红书", YOUTUBE: "YouTube", X: "X", DOUYIN: "抖音" };

export default function ImportsClientPage() {
  const router = useRouter();
  const [sources, setSources] = useState<Source[]>([]); const [sourceId, setSourceId] = useState(""); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [batchId, setBatchId] = useState(""); const [operationKey, setOperationKey] = useState(""); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [completed, setCompleted] = useState(false);
  const selectionVersion = useRef(0); const previewRequest = useRef(0); const operationKeyRef = useRef("");
  useEffect(() => { fetch("/api/sources").then(async (response) => { if (response.status === 401) { router.push("/login"); return; } if (!response.ok) throw new Error("来源列表加载失败"); const data = await response.json(); setSources(data.items); }).catch((err) => setError(err instanceof Error ? err.message : "来源列表加载失败，请检查网络连接")); }, [router]);
  function resetSelection(nextFile: File | null, nextSourceId: string) { selectionVersion.current += 1; previewRequest.current += 1; operationKeyRef.current = ""; setFile(nextFile); setSourceId(nextSourceId); setPreview(null); setBatchId(""); setOperationKey(""); setSnapshot(null); setCompleted(false); setError(""); }
  function currentSelection() { return file && sourceId ? { file, sourceId, version: selectionVersion.current } : null; }
  async function previewFile() {
    const selected = currentSelection(); if (!selected) { setError("请选择获准来源和 CSV 文件"); return; }
    const key = operationKeyRef.current || crypto.randomUUID(); operationKeyRef.current = key; setOperationKey(key); const selectedSnapshot = { file: selected.file, sourceId: selected.sourceId, operationKey: key }; setSnapshot(selectedSnapshot); setBusy(true); setError(""); setPreview(null); setBatchId(""); setCompleted(false);
    const version = selected.version; const requestId = ++previewRequest.current; const form = new FormData(); form.set("file", selected.file); form.set("sourceId", selected.sourceId);
    try { const response = await fetch("/api/imports/preview", { method: "POST", headers: { Origin: window.location.origin }, body: form }); const data = await response.json(); if (response.status === 401) { router.push("/login"); return; } if (!response.ok) throw new Error(data.message ?? "预览失败"); if (selectionVersion.current === version && previewRequest.current === requestId && file === selected.file && sourceId === selected.sourceId) setPreview(data); } catch (err) { if (selectionVersion.current === version && previewRequest.current === requestId) setError(err instanceof Error ? err.message : "预览失败"); } finally { if (selectionVersion.current === version && previewRequest.current === requestId) setBusy(false); }
  }
  async function submitImport() {
    const selected = currentSelection(); const key = operationKeyRef.current || operationKey; if (!selected || !preview || !snapshot || snapshot.file !== selected.file || snapshot.sourceId !== selected.sourceId || !key || snapshot.operationKey !== key || completed) { setError("请基于当前文件和来源重新预览后再提交"); return; }
    setBusy(true); setError(""); const form = new FormData(); form.set("file", selected.file); form.set("sourceId", selected.sourceId);
    try { const response = await fetch("/api/imports", { method: "POST", headers: { Origin: window.location.origin, "Idempotency-Key": key }, body: form }); const data = await response.json(); if (response.status === 401) { router.push("/login"); return; } if (!response.ok) throw new Error(data.message ?? "导入失败"); setBatchId(data.item.id); setCompleted(true); } catch (err) { setError(err instanceof Error ? err.message : "导入失败"); } finally { setBusy(false); }
  }
  function downloadTemplate() { const blob = new Blob(["platform,nativeId,displayName,profileUrl,organization,serviceTags,region,sourceUrl\nYOUTUBE,demo-001,演示财富规划机构,https://example.com/demo/youtube/001,演示机构,海外资产配置|财富规划,新加坡,https://example.com/demo/source/001\n"], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "accounts-template.csv"; anchor.click(); URL.revokeObjectURL(url); }
  return <main className="page"><div className="page-header"><div><h1 className="page-title">导入中心</h1><p className="page-subtitle">先预览，再提交。每批导入最多 500 行、2 MiB；只接受账号资料，不接受联系方式列。</p></div><button className="button secondary" onClick={downloadTemplate}>下载 CSV 模板</button></div><section className="card"><div className="form-grid"><div className="field"><label htmlFor="source">获准数据来源</label><select id="source" value={sourceId} onChange={(e) => resetSelection(file, e.target.value)}><option value="">请选择来源</option>{sources.map((source) => <option key={source.id} value={source.id} disabled={source.status !== "APPROVED" || !source.allowImport}>{source.name}（{source.status === "APPROVED" && source.allowImport ? "可录入" : "未获准"}）</option>)}</select></div><div className="field"><label htmlFor="file">CSV 文件</label><input id="file" type="file" accept=".csv,text/csv" onChange={(e) => resetSelection(e.target.files?.[0] ?? null, sourceId)} /></div><div className="notice full">上传主页链接只做本地格式和平台路径校验，不会由服务器访问、展开或抓取链接。</div>{error ? <div className="notice error full" role="alert">{error}</div> : null}<div className="form-actions full"><button className="button" onClick={() => void previewFile()} disabled={busy || !file || !sourceId}>{busy ? "处理中…" : "预览导入"}</button></div></div></section>{preview ? <section className="card" style={{ marginTop: 18 }}><div className="page-header" style={{ marginBottom: 14 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>预览结果</h2><p className="page-subtitle">共 {preview.totalRows} 条数据行，以下展示前 20 行；预览阶段未写入数据库。</p></div><button className="button" onClick={() => void submitImport()} disabled={busy || completed}>{completed ? "已提交" : "确认导入有效行"}</button></div>{preview.errors.length ? <div className="notice error">发现 {preview.errors.length} 条可定位错误；提交后有效行会继续导入，无效行会保留为失败结果：{preview.errors.slice(0, 10).map((item) => `第 ${item.rowNumber} 行 ${item.errorMessage ?? item.errorCode}`).join("；")}{preview.errors.length > 10 ? "；其余错误可在导入结果中查看" : ""}</div> : null}<div className="table-wrap"><table><thead><tr><th>CSV 行</th><th>状态</th><th>平台</th><th>账号名称</th><th>主页</th><th>说明</th></tr></thead><tbody>{preview.preview.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td><span className={`badge ${row.status === "READY" ? "success" : row.status === "DUPLICATE" ? "neutral" : "danger"}`}>{row.status}</span></td><td>{row.platform ? platformLabels[row.platform] : "—"}</td><td>{row.displayName ?? "—"}</td><td className="mono">{row.profileUrl ?? "—"}</td><td>{row.errorMessage ?? "—"}</td></tr>)}</tbody></table></div></section> : null}{batchId ? <div className="notice success" style={{ marginTop: 18 }}>导入已完成：<Link className="text-link" href={`/imports/${batchId}`}>查看导入结果</Link></div> : null}</main>;
}
