"use client";

import { FormEvent, useEffect, useState } from "react";

type Source = { id: string; name: string; type: string; status: string; permissionNote: string; allowImport: boolean; expiresAt: string | null; createdAt: string };
const typeLabels: Record<string, string> = { DEMO: "演示来源", AUTHORIZED_MANUAL: "经授权人工来源" };

export default function SourcesPage() {
  const [items, setItems] = useState<Source[]>([]); const [name, setName] = useState(""); const [type, setType] = useState("AUTHORIZED_MANUAL"); const [permissionNote, setPermissionNote] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/sources"); if (response.ok) { const data = await response.json(); setItems(data.items); } }
  useEffect(() => { queueMicrotask(() => { void load(); }); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const response = await fetch("/api/sources", { method: "POST", headers: { "Content-Type": "application/json", Origin: window.location.origin }, body: JSON.stringify({ name, type, permissionNote }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "来源创建失败"); setName(""); setPermissionNote(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "来源创建失败"); } finally { setBusy(false); } }
  async function change(id: string, patch: Record<string, unknown>) { setError(""); const response = await fetch(`/api/sources/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Origin: window.location.origin }, body: JSON.stringify(patch) }); const data = await response.json(); if (!response.ok) { setError(data.message ?? "来源更新失败"); return; } await load(); }
  return <main className="page"><div className="page-header"><div><h1 className="page-title">数据来源</h1><p className="page-subtitle">来源能力默认关闭；批准表示管理员登记/确认，不表示平台认证通过。</p></div></div><section className="card" style={{ marginBottom: 18 }}><h2 style={{ marginTop: 0, fontSize: 18 }}>登记新来源</h2><form className="form-grid" onSubmit={create}><div className="field"><label htmlFor="name">来源名称</label><input id="name" value={name} onChange={(e) => setName(e.target.value)} maxLength={160} required /></div><div className="field"><label htmlFor="type">来源类型</label><select id="type" value={type} onChange={(e) => setType(e.target.value)}><option value="AUTHORIZED_MANUAL">经授权人工来源</option><option value="DEMO">演示来源</option></select></div><div className="field full"><label htmlFor="permissionNote">允许录入依据说明</label><textarea id="permissionNote" value={permissionNote} onChange={(e) => setPermissionNote(e.target.value)} maxLength={2000} placeholder="记录来源、授权范围和用途依据；批准前必须填写。" /></div>{error ? <div className="notice error full">{error}</div> : null}<div className="form-actions full"><button className="button" disabled={busy}>{busy ? "保存中…" : "创建 DRAFT 来源"}</button></div></form></section><section className="card"><div className="table-wrap"><table><thead><tr><th>名称</th><th>类型</th><th>状态</th><th>录入能力</th><th>依据说明</th><th>操作</th></tr></thead><tbody>{items.length ? items.map((source) => <tr key={source.id}><td>{source.name}</td><td>{typeLabels[source.type] ?? source.type}</td><td><span className={`badge ${source.status === "APPROVED" ? "success" : source.status === "REVOKED" ? "danger" : "warning"}`}>{source.status}</span></td><td>{source.status === "APPROVED" && source.allowImport ? <span className="badge success">允许录入</span> : <span className="badge neutral">关闭</span>}</td><td className="pre-wrap" style={{ maxWidth: 360 }}>{source.permissionNote || "—"}</td><td><div className="inline-actions">{source.status !== "APPROVED" ? <button className="button" onClick={() => void change(source.id, { status: "APPROVED", allowImport: true })}>批准录入</button> : <button className="button danger" onClick={() => void change(source.id, { status: "REVOKED", allowImport: false })}>撤销</button>}</div></td></tr>) : <tr><td colSpan={6} className="empty">暂无来源，请先登记。</td></tr>}</tbody></table></div></section></main>;
}
